### ISSUE TITLE
クラス型のstatic letは無視したい

### ISSUE THREAD

**Issue by omochi** [omochi/CodableToTypeScript#103]
```swift
class C {}

struct S {
  static let c = C()
}
```

これでエラーになるけど、 `static let` はそもそも変換の範疇にないので、
`C` が出てきても無視してほしい。

**Comment by sidepelican** [comment]
今日これ遭遇しました。ほしいですね

**Comment by omochi** [comment]
ああー遭遇してしまいましたか。。

緊急対応としては `static let` を `extension` に吐き出すという技があります。

**Comment by omochi** [comment]
get onlyなcomputed varにする技もあるな。

**Comment by omochi** [comment]
そもそも普通にプロパティに含めようとしてくるｗ

<img width="774" alt="スクリーンショット 2024-04-11 14 13 11" src="https://github.com/omochi/CodableToTypeScript/assets/312792/b1304c4e-2b4a-44d3-9178-c8f8b40bd976">

**Comment by omochi** [comment]
解決
