### ISSUE TITLE
typealiasの対応方法の検討

### ISSUE THREAD

**Issue by omochi** [omochi/CodableToTypeScript#41]
下記のようなケースに対応したい

```swift
struct User {
  typealias ID = GenericID<User>
}
```

依存 https://github.com/omochi/SwiftTypeReader/issues/23

**Comment by omochi** [comment]
仕様が悩ましい。

以下の入力Swiftソースに対して、
生成するTypeScriptコードの案を並べる。

```swift
struct User {
  typealias ID = GenericID<User>

  var id: ID
}
```

# 案1: コード生成時にエイリアス先に置換する

```ts
type GenericID<T> = string & { GenericID: never };

type User = {
  id: GenericID<User>
};
```

# 案2: エイリアス関係をTypeScript上で再構成する

```ts
type GenericID<T> = string & { GenericID: never };

type User_ID = GenericID<User>;

type User = {
  id: User_ID;
};
```

# 案3: エイリアス関係をTypeScript上でタグ付きの型にする

```ts
type GenericID<T> = string & { GenericID: never };

type User_ID = GenericID<User> & { User_ID: never };

type User = {
  id: User_ID;
}
```

---

# 評価

**案1**: 生成結果はシンプルになる。エイリアス元の名前が失われる。

**案2**: エイリアス関係がTypeScript上に再現されるので元コードのニュアンスに近い。
ただし、 #53 の問題があり、型システムとしてはあまりID型の恩恵がない。

**案3**: #53 の問題を解決して、ID型が区別できる。

```ts
type GenericID<T> = string & { GenericID: never };
type User_ID = GenericID<User> & { User_ID: never };
type Student_ID = GenericID<Student> & { Student_ID: never };
type User = {
  id: User_ID;
}
type Student = {
  id: Student_ID;
}

function useUserID(id: User_ID) {
    // 型エラーになる
    useStudentID(id);
}
function useStudentID(id: Student_ID) {}
```

しかし、Swiftに元々存在しない区別を導入しているので、
下記のようなケースでは問題が生じる。

```swift
// swift
typealias A = Int
typealias B = Int

func useA(_ a: A) {
  // OK
  useB(a)
}
func useB(_ b: B) {}
```

```ts
// ts
type B = number & { B: never };

function useA(a: A) {
  // NG
  useB(a)
}
function useB(b: B) {}
```

**Comment by omochi** [comment]
@sidepelican 
どう思いますか？

僕は案3は問題を別のところで解決しようとして別の問題が生じているので微妙で、
#53 を妥協して案2にするのがマシだと思います。

**Comment by sidepelican** [comment]
#53 の問題は `GenericID<T>` の問題であって、typealiasの有無に関係なく起こるので、typealiasは #53 を無視してもいいと思いました。
typealiasの機能としては案1か案2がSwiftの機能に近い状態で表せていていいと思いました。

ここでtypealias側でなにかサポートがないと `GenericID<T>` が機能しない場合はそれ単体で使用したときに機能しなくなってしまうはずなので、そうなると状況がよりややこしくなるため何もしないほうがいいと思いました
