### ISSUE TITLE
Optional, Array, Dictionaryのtypetagを考える

### ISSUE THREAD

**Issue by omochi** [omochi/CodableToTypeScript#60]
この実装
https://github.com/omochi/CodableToTypeScript/issues/53#issuecomment-1351336423
だと、Optional, Array, Dictionaryのtype tagが定義できていない。

Optionalは1重の場合はフィールドなら `?:` による `T | undefined`、それ以外では `T | null`。
2重の場合はフィールドなら `?:` と合わせて `T | null | undefined`、それ以外では `T | null`。
3重以上は現れない。

Arrayは `T[]`、 Dictionaryは `{ [key: string]: T }` にトランスパイルしている。

ArrayなどはこのようにTypeScriptのArrayに対応付けたほうが、
`T[]` に対する操作が自在にできて便利なので、これ自体はtype tagを付けた専用の型を作らないのが良いだろう。

なお、 `T[]` と `U[]` の代入互換性については、 `T` と `U` それぞれがtype tagを持っていれば、
そこで代入不可になるので問題ない。

現状の問題は (不自然な例だが) `ID<User[]>` などがタグ無しになってしまう事。
なので、 `TagOf` が3つの場合(4つ？5つ？)について動作すれば良い。
通常 `TagOf` は既に合成されている TagRecord の内部からタグを抽出するオペレータとして実装されるが、
これらのケースでは合成されているTagRecordがないので、
このオペレータが `"Array" & ["User"]` といったタグをその場で生成するのが求められる。
実装の形としては conditional type をネストした形になるだろうが、
果たしてうまく書けるのか不明。

**Comment by sidepelican** [comment]
なるほど、ジェネリックパラメータの中間にタグ無し型が挟まるとそこでタグが途絶えてしまうんですね

タグを意図的につけない型が限定できるのであればそこだけ明示的に`TagOf`側でケアするのでどうでしょうか。

```ts
type TagOf<Type> = 
Type extends TagRecord<infer TAG> 
? TAG
: Type extends (infer E)[]
  ? "Array" & [TagOf<E>]
  : Type extends Record<string, infer E>
    ? "Dictionary" & [TagOf<E>]
    : never;
```

**Comment by omochi** [comment]
そうですね、構造はそういう感じでif(conditional type)のネストで良いと思います。

Arrayは良さそう。

DictinaryのRecordは他のケースを巻き込まないのだろうか？
末尾に書いてるので害は無さそう。

Optionalはどうすればいいんだろう。
`extends (infer E) | null` は valid っぽいですが、 
そもそも ただの `E` も is-a `E | null` なので、巻き込みそう。

あと、そのまま書いたら `TagOf` 自身が再登場する再帰にエラーが出ました。

**Comment by sidepelican** [comment]
う〜ん確かにOptionalは難しいですね・・・

**Comment by omochi** [comment]
これでできそう。

https://stackoverflow.com/questions/59626785/conditional-types-for-nullable-in-typescript

**Comment by sidepelican** [comment]
なるほど。

```ts
type TagOf<Type> = 
Type extends TagRecord<infer TAG>
? TAG
: Type extends (infer E)[]
  ? "Array" & [TagOf<E>]
  : Type extends Record<string, infer E>
    ? "Dictionary" & [TagOf<E>]
    : Type extends null
      ? "Null" & [TagOf<NonNullable<Type>>]
      : never;
```

これでうまくいきそう？

**Comment by omochi** [comment]
オプショナルのところextendsの前後が逆ですね

null is-a E | null を利用するので。

**Comment by omochi** [comment]
再帰のエラーは何かの勘違いでした、通りそう

**Comment by sidepelican** [comment]
う〜んやっぱりだめそうでした。

```ts
type DD = ID<Book | null>;
type EE = ID<Book>;

let dd: DD;
dd = "" as EE; // OK
let ee: EE;
ee = "" as DD; // NG
```

```ts
type DD = string & {
    $tag: "ID" & ["Book" | ("Null" & [never])];
}
type EE = string & {
    $tag: "ID" & ["Book"];
}
```

`"Book" | (...)`  に対して `"Book"` は代入できてしまうので、ここが `|` で繋がってしまうのが良くないですね。

**Comment by omochi** [comment]
あーまあそれはユニオンタイプにトランスパイルしてるからなので仕方ないかと
ID<Book | null>とID<Cat | null>を区別できないことが起票している課題です

**Comment by sidepelican** [comment]
なるほど。まあこのへんはしょうがないですね。現実的にこれで困るケースないと思うのでいいと思います

**Comment by omochi** [comment]
OptionalとArrayはうまく動いたんですが、Dictionaryがうまくいかないです。
@sidepelican 何かわかりますか？

```ts
export type TagOf<Type> = Type extends {
    $tag?: infer TAG;
} ? TAG 
: null extends Type 
? "Optional" & [TagOf<Exclude<Type, null>>]
: Type extends (infer E)[] 
? "Array" & [TagOf<E>]
: Type extends { [key: string]: infer V }
? "Dictionary" & [TagOf<V>]
: never;

export type TagRecord<Name extends string, Args extends any[] = []> = Args["length"] extends 0 ? {
    $tag?: Name;
} : {
    $tag?: Name & {
        [I in keyof Args]: TagOf<Args[I]>;
    };
};

export function identity<T>(json: T): T {
    throw 0;
}
export function Optional_decode<T, T_JSON>(json: T_JSON | null, T_decode: (json: T_JSON) => T): T | null {
    throw 0;
}
export function OptionalField_encode<T, T_JSON>(entity: T | undefined, T_encode: (entity: T) => T_JSON): T_JSON | undefined {
    throw 0;
}
export function Optional_encode<T, T_JSON>(entity: T | null, T_encode: (entity: T) => T_JSON): T_JSON | null {
    throw 0;
}

export type Date_JSON = string;
export function Date_decode(json: Date_JSON): Date {
    throw 0;
}
export function Date_encode(entity: Date): Date_JSON {
    throw 0;
}

type S = {
    a: string;
} & TagRecord<"S">

type K = {
    a: string;
} & TagRecord<"K">

type SD = { [key: string]: S };
type KD = { [key: string]: K };

type SA = S[];
type KA = K[];

type P<T> = {} & TagRecord<"P", [T]>;

type ID<T> = string & TagRecord<"ID", [T]>

type DicTest<T> = T extends { [key: string]: infer V } 
? TagOf<V> : false;
type A = DicTest<SD>

function useIDSD(a: ID<SD>) {
    useIDSD(a);
    useIDKD(a); // !!!
    useIDSA(a);
}

function useIDKD(a: ID<KD>) {
    useIDKD(a);
    useIDSD(a); // !!!
}

function useIDSD2(a: ID<{ [k: string]: S }>) {
    useIDSD2(a);
    useIDKD2(a);
}

function useIDKD2(a: ID<{ [k: string]: K }>) {
    useIDKD2(a);
    useIDSD2(a);
    useIDKA(a);
}

function useSO(a: S | null) {
    useSO(a);
    useS(a);
    useIDS(a);
}

function useS(a: S) {
    useS(a);
    useSO(a);
}

function useK(a: K) {
    useS(a);
}

function useIDSO(a: ID<S | null>) {
    useIDSO(a);
    useIDS(a);
}
function useIDKO(a: ID<K | null>) {
    useIDSO(a);
}

function useIDSA(a: ID<SA>) {
    useIDSA(a);
    useIDKA(a);
}

function useIDKA(a: ID<KA>) {
    useIDK(a);
    useIDSA(a);
}

function useIDS(a: ID<S>) {
    useIDSO(a);
}




function useIDK(a: ID<K>) {
    useIDS(a);
}

function useIDPS(a: ID<P<S>>) {
    useIDPK(a);
}

function useIDPK(a: ID<P<K>>) {

}
```

**Comment by sidepelican** [comment]
むむ、シンプルなケースだとうまく判定できてるので不思議ですね

```ts
type Test<T> = T extends { [key: string]: infer V } ? V : false;
type Use1 = Test<{ [key: string]: number }>; // number
```

**Comment by omochi** [comment]
むむ
<img width="368" alt="スクリーンショット 2022-12-27 21 50 18" src="https://user-images.githubusercontent.com/312792/209669213-5d0fa531-9e82-4ecc-bd73-ad984fff3f0d.png">

**Comment by sidepelican** [comment]
一番上の
```ts
Type extends {
     $tag?: infer TAG;
}
```

に `{ [key: string]: infer V }`が吸われちゃってるように思いました。
回避できるのかな。。。

**Comment by omochi** [comment]
`{ [key: string]: ... }` が `extends { $tag?: infer X }` にマッチしてしまうっぽい

**Comment by omochi** [comment]
あ、同時

**Comment by sidepelican** [comment]
```ts
Type extends {
     $tag?: infer TAG;
}
```

を

```ts
(a: Type) => Type extends (a: infer TAG) => TagRecord<infer TAG>
```

にしたらうまくいった気がする？
代わりにマウスオーバーで表示される型情報がしょぼくなっちゃいました（最後まで掘ってくれなくなった）

**Comment by sidepelican** [comment]
関数型の引数ポジションに型パラを置くとcontravariantポジションで評価してくれるので返り値と合わせてinvariantで同じ型かどうかを評価してくれると思ったんですが、引数に置いてしまうと型情報が途切れてしまうというジレンマ・・・

**Comment by omochi** [comment]
`TagRecord<infer TAG>` は間違ってると思います
`TagRecord<"P", [T, U]>` などのようにして使うので、型パラになる第2パラメータが拾えていない

**Comment by omochi** [comment]
辞書型の定義に `$tag?:` を足してみようとしたけど `[key: string]` と矛盾するから駄目らしい
<img width="678" alt="スクリーンショット 2022-12-27 22 18 08" src="https://user-images.githubusercontent.com/312792/209672385-dc7ef5b3-44dd-4f8a-bab6-f52e811e4a2f.png">

**Comment by sidepelican** [comment]
第二パラメーターを拾う必要はなくないですか？
第二パラメーターは各型についてるTagRecordが既に展開済みなので第一パラメーターに既に埋め込まれてると思います

**Comment by omochi** [comment]
たしかにうまく抽出できるようなので調べてみました。

```ts
type C1<T> = T extends TagRecord<infer TAG> ? TAG : false;
type C2 = C1<P<S>>
// "P" & ["S"]
```

`extends` の右側の `TagRecord` の中身を `Name := infer TAG` で置換した結果で展開してから処理するため、
元の定義の `$tag?: Name` が `$tag?: infer TAG` になって全部取り出せるようです。

この際 `TagRecord<infer TAG>` の第2パラメータがデフォルトの `[]` になっている事がポイントで、
`TagRecord` の `Args.length` の判定で 0 の分岐に入っているからうまくいくようでした。

試しに `TagRecord` の定義を下記のように0の特別分岐を外したところ、

```ts
export type TagRecord<Name extends string, Args extends any[] = []> = {
    $tag?: Name & {
        [I in keyof Args]: TagOf<Args[I]>;
    };
};

type C1<T> = T extends TagRecord<infer TAG> ? TAG : false;
type C2 = C1<P<S>>
// false
```

`C2` の評価結果が変化しました。

**Comment by omochi** [comment]
> 関数型の引数ポジションに型パラを置くとcontravariantポジションで評価してくれるので返り値と合わせてinvariantで同じ型かどうかを評価してくれると思ったんですが

↑この文は理解できて

> (a: Type) => Type extends (a: TagRecord<infer TAG>) => TagRecord<infer TAG>

↑の `extends` 条件は

```ts
type E1<Type> = Type extends TagRecord<infer TAG>
type E2<Type> = TagRecord<infer TAG> extends Type
```
↑この2つの条件を解かせるということだと思うのですが・・・

`Type` には例えば

```ts
type S = {
  name: string;
} & TagRecord<"S">
```

の `S` などが来るので、

`S extends TagRecord<infer TAG>` は真ですが、
逆の `TagRecord<infer TAG> extends S` は成り立たないので、
そもそもの `TagOf` の機能が消えてしまってそうです。

**Comment by omochi** [comment]
Dictionaryはあらゆる `key: string` を受け付けるのに対して、Objectは特定のプロパティしか受け付けない事を利用して、
両者を区別できる式を書けないだろうか・・・？

**Comment by omochi** [comment]
```ts
type TestDict<T> = T extends {
    [key: string]: infer V
} ? true : false
type C1 = TestDict<S>
// true
```

逆の判定もまたしかりなのか・・・
`S.a: string` しかプロパティを持ってないけど、
`[key: string]` は「あらゆるkey」ではなくて、
「自身のもつ全てのkey」の意味なのか。

**Comment by sidepelican** [comment]
> 逆の TagRecord<infer TAG> extends S は成り立たないので、

確かに、本体の型のほうをうまく表せてないのでダメでした・・・

`$tag?` を `$tag` にしてundefinedを外せば `{ [key: string]: T } extends { $tag: infer TAG }` は満たせなくなるので、うまく動きそうですね。
undefinedを外しても実用上の変化は気になりますが。
基本的にタグが付いた型を作るときは `as S` を通す形になるので、`as S` の警告が出る範囲が変わる部分に影響が出そうです

```ts
const s: S = {
    a: "S",
    i: "", // 余計なプロパティがあると$tagがないと言われて怒られる（なぜ？）
} as S;

const t: S = {
    a: "S",
} as S; // $tagはないけど許されてる（これもなぜ？）
```

**Comment by omochi** [comment]
$tag?: プロパティを調べる方法だと、
これの型は
「stringまたはstring & tuple」またはundefinedなので、
前者のstring | undefinedのケースがよくある値が文字列のディクショナリと衝突しますね。

$tagをいったんオブジェクトにして
{ kind: "tag", value: 従来のタグの値 }
とすれば、
$tag.kindを調べる分岐で通常の型は区別できそう・・・

その先でディクショナリなのか、タグのついてないJS側の型なのか、の区別も必要だけど、同じ問題を踏む気がする。

**Comment by omochi** [comment]
> $tag? を $tag にしてundefinedを外せば { [key: string]: T } extends { $tag: infer TAG } は満たせなくなるので、うまく動きそうですね。

これは選択肢の一つですね
しかし実際にはタグをもたない値をasで押し切るのはキャストができない場合があるんですね。
ランタイムの値として実際にタグを持たせるのが丸いけど，その場合型のinitとcopyを提供してあげる必要がありそうですねえ。

**Comment by sidepelican** [comment]
そういえば{[k:string]:T}は諦めてMapとしてトランスパイルする手はありそうですね。エンコード・デコードできるわけですし。

**Comment by omochi** [comment]
たしかに・・・
それは良いアイデアですね
entity typeとしてその方がお行儀が良い

**Comment by omochi** [comment]
できた
