### ISSUE TITLE
デモをローカルで動かす

### ISSUE THREAD

**Issue by omochi** [omochi/CodableToTypeScript#84]
デプロイの都合でbaseの設定をした事でローカルは壊れた気がする

**Comment by sidepelican** [comment]
viteがbaseを考慮した状態でdevサーバやpreviewをしてくれるので、壊れてなさそうです

**Comment by omochi** [comment]
マジか。後で確認します。
そうかdevサーバーはドメイン部分も掌握してるから辻褄合わせてくれるのか？

**Comment by omochi** [comment]
元々 
```
$ cd dist
$ npx serve
```
で見ていた。これはだめだった。

```
$ npm run preview
```
ならちゃんと見れた。
