### ISSUE TITLE
TagOfの実装が間違っている

### ISSUE THREAD

**Issue by sidepelican** [omochi/CodableToTypeScript#89]
以下の入力をして、AAAA~CCCCの型がどうなっているか見てみるといろいろ壊れてることに気づくと思います。

```swift
struct User: Codable {
  var name: String
}

struct GenericID<T>: RawRepresentable {
  var rawValue: String
}

public typealias AAAA = GenericID<[User]>
public typealias BBBB = GenericID<User?>
public typealias CCCC = GenericID<[String: User]>
```

いろいろ試したところ、以下の形が正しそうです

1. 最初のConditional Typeでは`[]`で要素数1のタプル化を行う。`T | null` が分割されるのを防ぐ。
2. 各々の派生タグを`[]`で囲む。ジェネリックパラメータのタグはTagRecord側でタプル型にまとまることになっていて、ルールがあっていませんでした

```ts
type TagOf<Type> = [Type] extends [TagRecord<infer TAG>]
    ? TAG
    : null extends Type
        ? "Optional" & [TagOf<Exclude<Type, null>>]
        : Type extends (infer E)[]
            ? "Array" & [TagOf<E>]
            : Type extends Map<infer K, infer V>
                ? "Dictionary" & [K, TagOf<V>]
                : never;
```

**Comment by omochi** [comment]
> いろいろ試したところ

ここをちゃんとテストコードで検証した方が良さそうですね。
最近の改修で、生成されたコードをTypeScriptコンパイラで型チェックをするようにしたのですが、
タグシステムの正しさに関しては、
そうした生成コードを「使うコード」をいろいろ書かないと検証できないのでテストされていません。

そのためのテストのインフラを追加しようと思います。

**Comment by sidepelican** [comment]
そうですね、僕の手元の作業の再現性がなくてデグレを起こす可能性もあるので好ましくない
ちなみにいまある `npx tsc` を使う仕組みは僕の手元だとめっちゃ怒られるので切ってます。Swiftからtscを動かす方法ぱっと思いつかないですね

![スクリーンショット 2023-01-18 12 34 56](https://user-images.githubusercontent.com/19257572/213077432-4346228e-2543-43a6-9822-82bf9459660f.png)

こういう表示がたくさん出る

**Comment by omochi** [comment]
```
$ npm install -g typescript
```

すると動くようになると思います。

その警告は

```
$ npm install tsc
```

したときに出る警告なので、
`npx tsc` が、tsc不在で `npm install tsc` を試みた結果そうなるのかと予想します。

ただまあグローバルインストールは好ましくないと思っているので良い方法があれば知りたいです。

**Comment by omochi** [comment]
現状。だめだこりゃ。

<img width="496" alt="スクリーンショット 2023-01-18 13 46 57" src="https://user-images.githubusercontent.com/312792/213086500-46ea584a-6f35-4772-beb8-716f5be7bd98.png">
<img width="517" alt="スクリーンショット 2023-01-18 13 47 02" src="https://user-images.githubusercontent.com/312792/213086489-13369eee-d618-4ef4-a8b2-21ee0a0f4307.png">
<img width="493" alt="スクリーンショット 2023-01-18 13 47 06" src="https://user-images.githubusercontent.com/312792/213086483-f5599da4-4297-4829-85a0-dad4fe231141.png">

**Comment by omochi** [comment]
これどーしてこーなるんだ？

<img width="511" alt="スクリーンショット 2023-01-18 14 07 08" src="https://user-images.githubusercontent.com/312792/213088996-72a4e0cc-fbe3-4922-85d3-07f04fbd2138.png">

**Comment by omochi** [comment]
分配法則というのが使われるらしい。
https://numb86-tech.hatenablog.com/entry/2020/07/02/103544

```
TagOf<User | null> 
  = User extends ... | null extends ...
  = "User" | never 
  = "User"
```

ということか。マジかよ。

**Comment by omochi** [comment]
1要素タプルに包むことで分配法則を無効化できることを理解した

**Comment by omochi** [comment]
> 各々の派生タグを[]で囲む。ジェネリックパラメータのタグはTagRecord側でタプル型にまとまることになっていて、ルールがあっていませんでした

ああそうか。
型パラメータの中身はタプルに入れるはずなのに、`TagOf` はその中身を出してるからか。
これはしょぼい間違いだった。
