### ISSUE TITLE
定数Genericパラメータに対するCodableのPresenceが評価されない

### ISSUE THREAD

**Issue by sidepelican** [omochi/CodableToTypeScript#94]
以下のようなコードを考えます。

```swift
enum A {}

enum S {
    case a(T<A>)
}
struct T<U> {
  var u: U
}
```

<details>
<summary>
TS生成結果
</summary>

```ts
export type A = never;

export type S = {
    kind: "a";
    a: {
        _0: T<A>;
    };
} & TagRecord<"S">;

export type S_JSON = {
    a: {
        _0: T<A>;
    };
};

export function S_decode(json: S_JSON): S {
    if ("a" in json) {
        const j = json.a;
        const _0 = j._0 as T<A>;
        return {
            kind: "a",
            a: {
                _0: _0
            }
        };
    } else {
        throw new Error("unknown kind");
    }
}

export type T<U> = {
    u: U;
} & TagRecord<"T", [U]>;

export type T_JSON<U_JSON> = {
    u: U_JSON;
};

export function T_decode<U, U_JSON>(json: T_JSON<U_JSON>, U_decode: (json: U_JSON) => U): T<U> {
    const u = U_decode(json.u);
    return {
        u: u
    };
}

export function T_encode<U, U_JSON>(entity: T<U>, U_encode: (entity: U) => U_JSON): T_JSON<U_JSON> {
    const u = U_encode(entity.u);
    return {
        u: u
    };
}

```

</details>

Tはジェネリックですが、Sにおける利用箇所では型が既に埋まっている状態（`T<A>`）です。
実質NeverであるAはCodableにおける表現を持たないため、`T<A>`、及びSもCodableにおける表現を持てないと判断できます。
しかしS_decodeは生成されています。
TがCodableかどうかはUによって決まるため判断できませんが、SがCodableかどうかは判断できるべきだと思いました。

**Comment by omochi** [comment]
Neverの伝搬を考える必要がありますね。
1.Enumのcaseがない場合
2.Enumの全てのcaseがNeverの場合
3.Structの一部のプロパティがNeverの場合
その型はJSON表現を持たない
JSON表現を持たない型はデコードもエンコードもできない
という規則の追加が必要そう

今のところJSON表現を持たないという概念がないのでneverなエンティティのjson表現もneverという出力になってますね
ちなみに現状の実装のhasJSONType==falseはそれっぽい名前ですがエンティティとJSONが同一という別の意味です

**Comment by sidepelican** [comment]
> JSON表現を持たないという概念がない

なるほど？これ例をneverにしちゃいましたが、実際に遭遇したのは未定義型（つまり`A`が未定義）のケースだったんですよね。
`A`が未定義だからどうあがいても`S`のhasJSONType判定ができないのに、なぜか貫通してしまって困った感じでした

**Comment by omochi** [comment]
型が解決できてない場合の挙動はライブラリとしては今のところハッキリ決められてないですね
例外が飛んだりスルーしたりするのかな・・・？

基本的には利用側でちゃんとコードを読み込ませて、知らない型は出てこないようにしてほしいと思っています

もしそれを許容したいのであれば、生成器がどういう挙動をするのが望ましいか、具体例と共に検討したいです

**Comment by omochi** [comment]
この話の流れだと、不明な型もneverの一種であり、json表現を持たない、とするのが良いのかな

**Comment by sidepelican** [comment]
型が解決できない場合の挙動としてはエラーを投げて止まる方向で統一されていたいなと思っています

> 基本的には利用側でちゃんとコードを読み込ませて、知らない型は出てこないようにしてほしい

そうありたいんですが https://github.com/omochi/CodableToTypeScript/pull/93 に関連する話で、そもそもエラーになっていないのでエラーを出せないんですよね。

具体例はここで、　https://github.com/sidepelican/CodableToTypeScript/blob/6420d148498458ae9d49a2c556ed66f3218099db/Tests/CodableToTypeScriptTests/Generate/GenerateErrorTests.swift#L71 この入力コードに対してエラーを出せるようにしたいです。今もエラーは出ますが、エラーが出るレイヤがautoImportDeclのステージなので #93 の目的としては嬉しくないんですよね

> この話の流れだと、不明な型もneverの一種であり、json表現を持たない、とするのが良いのかな

持つか持たないか解決不能なのでエラーにしたいですね

**Comment by sidepelican** [comment]
#95 でテストを書いたのですが、CodecPresenceに関してSubstitutionは正しく動いてそうでした。
https://github.com/omochi/CodableToTypeScript/issues/94#issuecomment-1418883726 で述べたケースにおいて期待通りに動かないのは別の要因がありそうでした。このIssueの疑問は勘違いだったためこれは閉じます
